---

- name: Update add-apt-repository -y ppa:pi-rho/dev
  apt_repository: repo=ppa:pi-rho/dev

- name: update
  apt: update_cache=true

- name: install
  apt: pkg={{ item }} #update_cache=true
  with_items:
    - git-core
    - ssh
    - ruby
    - ruby-dev
    - rubygems-integration
    - build-essential
    - curl
    - m4
    - texinfo
    - libbz2-dev
    - libcurl4-openssl-dev
    - libexpat-dev
    - libncurses-dev
    - zlib1g-dev
    - python-software-properties
    - software-properties-common
    - libpcre3
    - libpcre3-dev
    - openssl
    - zsh
  sudo: yes

- name: install
  apt: pkg={{ item }} #update_cache=true
  with_items:
    - nodejs
    - nodejs-legacy
    - npm
  sudo: true
