---

# This is a task. Basically, it needs a module command. In this example, it
# also have a `name`, which will be displayed while running the task to give a
# better description of the running task.

- include: debug.yml tags=debug

- include: base-install.yml tags=ubuntu
  when: is_ubuntu

- include: mac-os-base.yml tags=osx
  when: is_mac_os

- include: node.yml tags=node
- include: zsh.yml tags=zsh
- include: dotfiles.yml tags=dotfiles
- include: apps.yml tags=apps